services:
  archetype:
    build:
      context: .
      dockerfile: archetype.dockerfile
    container_name: archetype
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=container
      - ENVIRONMENT=container
    networks:
      - platform

networks:
  platform:
    driver: bridge
